### ISSUE TITLE
TUI ListView: action toolbar truncated. right align it?

### ISSUE THREAD

**Issue by joebordes** [tsolucio/corebos#1026]
![FireShot Capture 1119 - Administrator - To Dos - coreBOS - localhost](https://user-images.githubusercontent.com/1237191/112749515-03cb9380-8fc3-11eb-89b0-2e36e357c646.png)

**Comment by Luke1982** [comment]
I don't really like the way this is done now. LDS has default solutions for this, will implement that.

**Comment by joebordes** [comment]
LGTM

**Comment by denaldhushi** [comment]
This looks good, but what concerns me and the reason why I made it in inline buttons was because if the user want to click in the actions in the second row for example, the user need to click in the listview body to close the "actual" dropdown list and to open another one.
![1](https://user-images.githubusercontent.com/20266205/114315011-5f3a6d00-9afd-11eb-8915-7dea437edd00.png)

**Comment by Luke1982** [comment]
Yes, that is true but that is by design of the LDS menu. I understand your concern but in my experience with these menu's I don't think what will be a big issue.
