### ISSUE TITLE
Datetimecomparison only feeds 6 arguments when 7 are needed

### ISSUE THREAD

**Issue by Luke1982** [tsolucio/corebos#1147]
https://github.com/tsolucio/corebos/blob/54e4378d2794e7a0413e56d3e6131e0f649f1183/include/js/general.js#L1673
https://github.com/tsolucio/corebos/blob/master/include/js/general.js#L572

I'm trying to use the built-in validation to check one datetime field against another but can't figure out how to structure the typeofdata column. I don't understand how this can work when the calling function doesn't provide the type of comparison that needs to be done.

**Comment by joebordes** [comment]
I just had another look at this using the existing definition in Assets where Date in service has to be greater or equal to date sold:

`D~M~OTH~GE~datesold~Date Sold`

the execution starts on [line 1704, dateComparison](https://github.com/tsolucio/corebos/blob/master/include/js/general.js#L1704), from there it continues on [line 822 compareDates](https://github.com/tsolucio/corebos/blob/master/include/js/general.js#L822) where type is GE

Since it seems to be working and it is documented on the wiki page above, I'm going to close the issue. Feel free to open it again and continue asking whatever you need.
