### ISSUE TITLE
Workflow to create Entity/Record in another Module

### ISSUE THREAD

**Issue by dfanaei** [tsolucio/corebos#1249]
Is there a way to create a workflow that can create a entity/record in another module other than tasks and other common modules that are already in the create entity options in the workflow?
For example, I want to execute a business action button (I followed one of your tutorials to create the action) to execute a workflow that creates a Project from an opportunity and copies all the fields. I also want to make all the related module records of the opportunity to get related to the project. and then delete the opportunity once the project is created.

if not possible, How can I create a convert button? like the convert Lead button that already exists but add it to the opportunity module.

**Comment by joebordes** [comment]
Hi

Yes, you can use the Upsert task for this purpose. Upsert, besides permitting updates, will permit the creation of records on any module. It is not restricted to the related modules.

As to copying the relations that will be more difficult.

First, you have to consider that you may have 1 to many relations which are easy as you "just" have to use the update related records task to update the uitype 10 field that establishes the relation. In this case, I would recommend a second relation field instead of overwriting the existing one so you don't lose the existing relation, but that is up to you and your business requirement.

For the many to many relations, you have to use the set many to many relations task but I'm not sure it supports the functionality you are asking for. I don't remember, but that is your first stop for those. Have a look and ask again.

Obviously, you have to make sure the destination module has the relations you need.

Finally, as a comment. I would not delete the origin record, at most [archive it](https://blog.corebos.org/blog/archiverecordpattern)

Let me know how it goes.

Have a nice weekend.

**Comment by dfanaei** [comment]
Ok Great! Thank you @joebordes 

Now, I see the workflow working. 
However, as I am trying to launch the Business action, It looks like it doesn't execute. 
as you explain in this video (10:35): https://www.youtube.com/watch?v=sRvU2SWtggY
I used the script below for the URL field and it is active for all users (correct Workflow ID). 
javascript:ExecuteFunctions('execwf','wfid=34&ids=$RECORDS$');
Is this correct?

**Comment by joebordes** [comment]
Hi

you have an extra "S", it is `$RECORD$`, `$RECORDS$`, that is why it doesn't find the record to launch the workflow with,

I see that you can use also `runBAWorkflow`, a little easier

`javascript:runBAWorkflow(12,$RECORD$);`

For reloading you have to force the reload of the page with `location.reload()', like this

``javascript:runBAWorkflow(12,$RECORD$);location.reload();`

**Comment by dfanaei** [comment]
Ok Perfect. Thank You.
