### ISSUE TITLE
List View Order

### ISSUE THREAD

**Issue by dfanaei** [tsolucio/corebos#1253]
Hi 
I am facing an issue for default list view. 
I have defined these global variables.  I need the list to show the latest records at the top of the list.
![image](https://user-images.githubusercontent.com/29267557/159591143-b3941e99-780e-43fc-a76f-c278edb79d78.png)

But unfortunately, it is not working regardless of what I do. 
This is what I'm getting instead. 
![image](https://user-images.githubusercontent.com/29267557/159591394-867a3170-2217-410e-9911-4e8cce12e15d.png)

**Comment by joebordes** [comment]
I tried this and it seems to be working. Note that this works ONLY the first time you visit the module and as long as you do not sort. Once you sort by any column that sorting stays selected until you log out.

**Comment by dfanaei** [comment]
Thanks @joebordes . It seems to be working now. But it didn't even though i did log out while I was trying to get it working. Perhaps a cache issue? But all good now for the list view. 
However, it seems that in the home screen when you add the module, it sorts out the records from oldest to newest. The problem is the newest ones will end up not even showing after some time as the number of records will add up to more than 12. 
How can I make it show the newest ones on top on the Home screen added filtered module?

**Comment by joebordes** [comment]
This is not supported at the moment. Mostly because of two reasons.

1.- the correct solution to this request is to add sorting functionality in the filter definition. So you should be able to indicate which fields you want to order by each filter when you define it. Then we would order by the chosen fields in the dashboard. This has been on our to-do list for a while now but we still haven't been able to get to it.

2.- we are also in the works of redesigning the dashboard/home page. this enhancement falls into that category also which we don't have the resources to get to

**Comment by dfanaei** [comment]
Ok thanks @joebordes . This would be a very helpful feature to add.
