### ISSUE TITLE
'cbwsExecuteWorkflowWithContext' incorrectly fails due to missing save permissions

### ISSUE THREAD

**Issue by Luke1982** [tsolucio/corebos#1362]
https://github.com/tsolucio/corebos/blob/8eeb660a171f0e22b6d6e52d038870428fdcd74c/include/Webservices/ExecuteWorkflow.php#L83

I use the `ModCommentsHandler.php` file to fire a workflow when a comment is saved using `cbwsExecuteWorkflowWithContext`. When I do so with users that are not admins, the `cbwsExecuteWorkflowWithContext` function throws a fatal error. When I remove
```php
isPermitted($workflow_mod, 'Save', $crmid)=='no'
```
it works. The users in question have profiles that are allowed to save comments (but not edit existing ones), so this is not due to incorrect profile settings.

**Comment by joebordes** [comment]
I think we are trying to follow a similar logic to other web service endpoints that don't let you access records if you don't have write permissions on them. That is restrictive because you could want to send out emails or other tasks that are non-destructive. So maybe we overdid it a little there.

I don't see any issue in eliminating that condition, so if you agree, I will do that.

**Comment by Luke1982** [comment]
Ah yes, I understand. I agree, you should be able to access records when you don't have write access. You just shouldn't be able to change them, which is what 'write' implicates. So removing this condition seems logical to me.
