### ISSUE TITLE
Please clarify system requirements for latest coreBOS 5.5.0.

### ISSUE THREAD

**Issue by ronankeane** [tsolucio/corebos#305]
I have an old install of this (the initial April release) that I would like to upgrade from coreBOS 5.4.0 to coreBOS 5.5.0.

a. Why is the link to upgrade from coreBOS 5.4.0 to coreBOS 5.5.0 struck out [on this webpage](http://corebos.org/documentation/doku.php?id=en:installupdate) 

b. On your ['Install CoreBOS' webpage](http://corebos.org/documentation/doku.php?id=en:install550) you have requirements:
- Apache 2.x or above.
- MySQL 5.x
- PHP from 5.4.x to 7.0.x. PHP 7.x is recommended.

However on your [latest release webpage](http://corebos.org/page/latest-release) you have:
- Apache 2.0.40 or above
- MySQL 5.1.x
- PHP from 5.3.x to 5.5.x

Please can someone clarify. Thank you.

**Comment by joebordes** [comment]
Hi

a)
Since we introduced [coreBOS Updater](http://blog.corebos.org/en/blog/corebos-updater2) the notion of [versions and migrations has disappeared](http://blog.corebos.org/en/blog/nomoreversions). The correct way to install coreBOS is cloning the GitHub repository using git and keep your install constantly up to date, I recommend at least once a month if not more frequently.

Since it makes no sense to talk about version numbers and there is no actual migration process, it is just, update your code from GitHub and apply coreBOS updates all the time forever, we have struck out the obsolete pages.

b)

The website is obsolete and being updated. We will totally eliminate that section from the website. What is maintained (as much as time permits) is the documentation site.

So the correct requirements are on the documentation wiki

HTH

**Comment by joebordes** [comment]
I am going to close this issue as it is more of a support question than an actual coreBOS issue. If you need more help please open a thread in the forum referencing this issue and I will try to help there.

Let us know how it goes.
