### ISSUE TITLE
Enhance GenDoc {foreach} to test more than one condition

### ISSUE THREAD

**Issue by Luke1982** [tsolucio/corebos#685]
https://github.com/tsolucio/corebos/blob/bebbf70e9967ea6b63960915b1323e15cb77069a/modules/evvtgendoc/compile.php#L658-L670

Right now, we can only limit the records returned to us in the {foreach} by one condition. I propose we enhance and extend the code and syntax to accommodate more conditions. Maybe something like:
```{foreach ModuleName [ModuleName.FieldName=value && ModuleName.CheckBox=1]}```
But anyway, something that will allow us to apply more than one condition to our loops.

**Comment by joebordes** [comment]
this is a very interesting idea
Kiko says that it shouldn't be that hard to do either and proposes even eliminating the "Modulename." from the conditional part and changing the brackets to parenthesis to support nested and/or statements.

Personally I think I would first have a look at using the workflow expression language or the webservice query format, or the filter condition format because these already have code to process all the edge cases of balancing parenthesis and accessing related record field values and because that way you can leverage the knowledge.

Not quite sure which would be the next step...

**Comment by Luke1982** [comment]
Well how would I start implementing the workflow expression language? I think that would be a good start

**Comment by Luke1982** [comment]
OK. so judging by [this](https://github.com/tsolucio/corebos/blob/bebbf70e9967ea6b63960915b1323e15cb77069a/modules/evvtgendoc/OpenDocument.php#L977) line here, we don't have to change any of the code that strips off the '{' and '}' or the 'foreach' keyword, that is all done for us and we can safely add parenthesis around our condition.

**Comment by joebordes** [comment]
That link evaluates a workflow expression, but I was thinking of the workflow conditions, not the expression language itself (sorry). So when you go to a workflow and you add the conditions where you select the fields and values and you can add groups...

that is saved in the database as a JSON string which can be evaluated easily as seen here:

https://github.com/tsolucio/coreBOSTests/blob/master/modules/com_vtiger_workflow/VTJsonConditionTest.php#L35

but the workflow has a visual editor to create the expression, in GenDoc we have to type it, so that takes to the same point, we need a parser to transform the written condition into that JSON string to be evaluated.

**Comment by Luke1982** [comment]
Ah yes, I understand. So basically what we would need:

- Adapt the '[eval_paracada](https://github.com/tsolucio/corebos/blob/bebbf70e9967ea6b63960915b1323e15cb77069a/modules/evvtgendoc/compile.php#L649)' function so that it can accomodate both the current way of conditioning (backwards compatibility) and a syntax that is as follows `{foreach ModuleName (fieldname=value && checkbox=1)}`. The function should, in the latter case decide:
- To hand of to a new function that incorporates the workflow condition engine and that takes a JSON formatted string like workflows normally pass to the engine to pass conditions.

Could you please evaluate this, since some of the code and comments are in Spanish, and sadly, I suck at Spanish?

**Comment by Luke1982** [comment]
As an addendum to the above: I see the function in use [here](https://github.com/tsolucio/corebos/blob/bebbf70e9967ea6b63960915b1323e15cb77069a/modules/evvtgendoc/OpenDocument.php#L1079) but can't really figure out exactly what effect it has.

**Comment by Luke1982** [comment]
Some notes:

The evaluate method of VTJsonCondition takes in a JSON formatted array of conditions. Example:
```json
[{"fieldname":"lm_payingmatter","operation":"is","value":"true:boolean","valuetype":"rawtext","joincondition":"and","groupid":"0"},{"fieldname":"lm_addition_no","operation":"is","value":"4","valuetype":"rawtext","joincondition":"and","groupid":"0"}]
```
The condition in 'eval_paracada' receives something like `CobroPago (paymentcategory=sometext && settled=1)` in the new form and `CobroPago.paymentcategory=sometext` in the old situation. We need to first tell which form is being used with a test function and delegate to the VTJsonCondition evaluate when the new form is true.

**Comment by Luke1982** [comment]
So just before [this](https://github.com/tsolucio/corebos/blob/master/modules/evvtgendoc/compile.php#L656) line we could add something like
```php
preg_match('/\w+\s\((.+)+\)/', $condition, $cond_elements); // Old or new style condition?
if (count($cond_elements) > 0 && isset($cond_elements[1])) {
	// New style
	include_once 'modules/com_vtiger_workflow/VTEntityCache.inc';
	include_once 'modules/com_vtiger_workflow/VTJsonCondition.inc';
	include_once 'modules/com_vtiger_workflow/VTWorkflowUtils.php';

	$util = new VTWorkflowUtils();
	$adminUser = $util->adminUser();
	$entityCache = new VTEntityCache($adminUser);
	$entityCache->forId($recordid);
	$cs = new VTJsonCondition();
	// Get the JSON formatted condition(s)!
	return $cs->evaluate($json_condition, $entityCache, $id);

	$util->revertUser();
}
```

**Comment by Luke1982** [comment]
OK, so a start has been made to get this working [in this PR](https://github.com/tsolucio/corebos/pull/686). We should be able to close this issue soon since the first version of 'multiple conditions' should go live then.

**Comment by joebordes** [comment]
I merged and tested the PR. I had a conflict with the foeach "IN" command:

`foreach Entity.field in (value1, value2)`

the parenthesis were conflicting with the new condition format so I had to change it to use square brackets instead like this:

`{foreach CobroPago [paymentcategory=MyPaymentCat && credit=1]}`

I made some other minor changes to optimize the code and eliminate warnings.

Give it a try and let me know how it goes. I'll leave the issue open sometime in case you run into anything but feel free to close it and open new ones.

Great addition!  Thanks!!
