### ISSUE TITLE
GlobalVariable_getVariable : Request is slow

### ISSUE THREAD

**Issue by mslokhat** [tsolucio/corebos#69]
Hi,

Ajax request for calling this function is slow 

45s -1min on a local server 

![image](https://cloud.githubusercontent.com/assets/8535048/12162347/31c72ecc-b51a-11e5-9304-ecae0fc0aaf0.png)

**Comment by joebordes** [comment]
Wow! That is slow. How many records do you have in the GlobalVarialbe table?

I attach a couple of screen shots on my system where I have 7 records and it is taking half a second.

![gvspeed01](https://cloud.githubusercontent.com/assets/1237191/12166781/92700484-b528-11e5-8afd-b6c75e05f0fe.png)
![gvspeed02](https://cloud.githubusercontent.com/assets/1237191/12166782/9274d78e-b528-11e5-907f-c93601adf99c.png)

I tried in the online demo where there are two records and the calls are a little under one second.

Give me some more information: what call are you making, how many users and GV records, what happens if you launch the same call in the TEST screen....

**Comment by mslokhat** [comment]
Hi,

i did not have any record , it seems to search for 3 variables
calendar_default_duration
calendar_other_default_duration
Calendar_Default_Reminder_Minutes

Once i have created them , the time is now 20-30s

I'm not making any call, anytime i select a listview or Editview it call these 3 variables

i have 10 users , but it's a dev server and noone is using the system.

is is possible to make the ajax call in background (asynchronous) so that it does prevent the page from loading?

the Page waits for these call to finish then the rest of the page is loaded. 
ie , User see a blank page for around 30-60s

**Comment by joebordes** [comment]
I investigated this a bit. I connected to a client of ours who has 258 users, 155 active. No global variables are defined. You can see in the attached screenshots that the timing is under half a second in firefox and under 1/4 of a second in chrome.

![gvslow03](https://cloud.githubusercontent.com/assets/1237191/12204050/4538c33a-b632-11e5-85c4-e6308deebf2e.png)
![gvslow04](https://cloud.githubusercontent.com/assets/1237191/12204051/453e1de4-b632-11e5-8deb-f14422667556.png)

I then looked into the call and found that we use native javascript which by default makes the calls synchronous (!!) as you very well indicate. I uploaded a commit to change that to asynchronous and the timings fell to half of what they were on both browsers (spectacular!!). Thank you VERY much for calling my attention to this :-)

Note that the values you see are miliseconds.

Give the change I made a try and get back to me.

**Comment by mslokhat** [comment]
Hi,

Thanks , yes , there is is an huge change

on the production server is fast : 

![image](https://cloud.githubusercontent.com/assets/8535048/12215716/8e9d49e2-b6e1-11e5-9238-afd62a1b5cb0.png)

Note : i'm using jquery 2.1.4 and have removed all prototype and scriptaculous librairies

**Comment by joebordes** [comment]
Glad that worked :-)

In this case I am using native javascript to avoid issues with jquery/prototype conflicts, so it doesn't matter.

In any case I saw your other issue and your email about jquery. I will look into the jquery move shortly and answer.

Have a nice weekend
