### ISSUE TITLE
merge duplicates, button delete exact - remove all registries with filed is blank

### ISSUE THREAD

**Issue by slemernet** [tsolucio/corebos#728]
For example, if you selected a email for comparation, system will remove not only emails equals, but all registries without any information in email ( blank )

https://discussions.corebos.org/showthread.php?tid=1730

**Comment by joebordes** [comment]
the "Delete Exact Duplicates" button will massively eliminate all the records in EACH group of duplicate values found except one. Note, this blindly deletes all records except one in each group so you may lose information.

That means that it is doing the expected behavior: not deleting all blanks but deleting all blanks EXCEPT one, just like for all the other groups.

There is a LOT of room for improvements in cleansing data and we are totally open to funding projects in this area (and many others), so feel free to sponsor the features you need.
