### ISSUE TITLE
mobile - when editin the ticket with mandatory relation not setting, system shows a error message

### ISSUE THREAD

**Issue by slemernet** [tsolucio/corebos#744]
My ticket have a "relation to" field setting as mandatory
Some tickets was created automatically from mail scanner and could be created without this information

when user intent changes any data in this ticket, system shows a error message, permission to performance operation is denied for this id
![mob3](https://user-images.githubusercontent.com/47395137/77330180-bb1d3280-6cfd-11ea-8288-d92d04f2c2e8.gif)

**Comment by omarllorens** [comment]
@joebordes the problem here is not Mobile module. Like say Ranieri, Mail scanner created a ticket without any value in related to field. This field is mandatory so when you try to edit and save this ticket, Mobile say you that you have not permission. So, for the actual Mobile working , this is correct. @slemernet  you have to check you mail scanner to know why is not putting any value in "Realted to" field.

Perhaps what is missing here is that this module had a validation by javascript to warn that there is an empty mandatory field, which I think it doesn't have.

**Comment by slemernet** [comment]
@omarllorens ok, is possible created specific message, at language files, to show a message more user friendly?

**Comment by joebordes** [comment]
Sorry, "related to" in support tickets is mandatory?

**Comment by joebordes** [comment]
ah, it is mandatory in his install. I tried it with a normal non-mandatory related to and it works correctly. So I understand that there should be a message there, no?

**Comment by slemernet** [comment]
Yes, if field is mandatory, not show correctly message, and call webservice anyway, today error message is shown thru web services

**Comment by joebordes** [comment]
closing
