### ISSUE TITLE
Undefined Index | When edit Workflow for Events when Send Notification is True

### ISSUE THREAD

**Issue by slemernet** [tsolucio/corebos#982]
: Undefined property: VTEmailTask::$attach_icalendar in
/var/www/clients/client1/web7/web/Smarty/templates_c/5edb1ae79c52a276a98f4cf0ee33638f7ca49905_0.file.VTEmailTask.tpl.php
on line 295 />

![img1](https://user-images.githubusercontent.com/47395137/102264410-5ab9cb00-3ef4-11eb-9001-ee6acff40d48.png)

**Comment by joebordes** [comment]
deactivate warnings, enter the workflow, it should show the correct screen, with all the fields correctly visible, save it
then you can activate warnings again and it should be ok
the issue is that we added functionality but can't update the tasks because each install may have changed it, rather complex and since you shouldn't have warning activated in production, it shouldn't be a problem

give it a try and let me know

**Comment by joebordes** [comment]
confirmed that the steps above fix the problem after this code change https://github.com/tsolucio/corebos/commit/375e885e11d0a9a28d891d7aefdc93c59ae88f2a
